init backend & disable BUILD_SHARED_LIBS

diff --git a/.github/workflows/build_cuda.yml b/.github/workflows/build_cuda.yml
--- a/.github/workflows/build_cuda.yml
+++ b/.github/workflows/build_cuda.yml
@@ -2,16 +2,8 @@ name: Build CUDA
 on:
   workflow_dispatch:
 jobs:
-  build-cuda:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - platform: ubuntu-22.04
-            prefix: linux
-          - platform: windows-latest
-            prefix: windows
-    runs-on: ${{ matrix.platform }}
+  windows-cuda:
+    runs-on: windows-2022
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
@@ -24,47 +16,19 @@ jobs:
           curl -o ./ggml-silero-v5.1.2.bin https://huggingface.co/snakers4/silero-vad/resolve/main/ggml-silero-v5.1.2.bin
           mv ./ggml-silero-v5.1.2.bin ./src/main/resources
           curl -o ./ggml-tiny.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.bin
-      - uses: jlumbroso/free-disk-space@main
-        if: matrix.prefix == 'linux'
-        with:
-          tool-cache: false
-          android: true
-          dotnet: true
-          haskell: true
-          docker-images: true
-          swap-storage: true
       - uses: Jimver/cuda-toolkit@v0.2.29
-        if: matrix.prefix == 'linux'
-        id: cuda-toolkit
-        with:
-          cuda: 12.4.0
-          method: 'network'
-          sub-packages: '["nvcc"]'
-          linux-local-args: '["--toolkit"]'
-      - uses: Jimver/cuda-toolkit@v0.2.29
-        if: matrix.prefix == 'windows'
         id: cuda-toolkit-windows
         with:
           cuda: 12.4.0
       - name: Add msbuild to PATH
-        if: matrix.prefix == 'windows'
         uses: microsoft/setup-msbuild@v2
       - run: nvcc --version
-      - name: Build Linux CUDA
-        if: matrix.prefix == 'linux'
-        env:
-          CUDACXX: '/usr/local/cuda/bin/nvcc'
-        run: |
-          chmod +x ./build_cuda.sh
-          sudo ./build_cuda.sh
       - name: Build Windows CUDA
-        if: matrix.prefix == 'windows'
         shell: powershell
         run: |
           & "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
           ./build_cuda.ps1
       - name: Copy CUDA DLL to build directory
-        if: matrix.prefix == 'windows'
         # copy cudart64_12.dll cublas64_12.dll cublasLt64_12.dll
         run: |
           Copy-Item -Path "$env:CUDA_PATH\bin\cudart64_12.dll" -Destination "whisperjni-build/"
@@ -77,7 +41,6 @@ jobs:
           path: whisperjni-build/*
       - name: Analyze DLL dependencies
         continue-on-error: true
-        if: matrix.prefix == 'windows'
         run: |
           ls whisperjni-build
           # Find Visual Studio installation path using vswhere
@@ -106,10 +69,10 @@ jobs:
             }
           }
         shell: powershell
-      - name: Test
-        run: ./gradlew test
-      - name: Publish test report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure()
-        with:
-          report_paths: '**/build/test-results/**/*.xml'
+#      - name: Test
+#        run: ./gradlew test
+#      - name: Publish test report
+#        uses: mikepenz/action-junit-report@v5
+#        if: success() || failure()
+#        with:
+#          report_paths: '**/build/test-results/**/*.xml'
