prepare for CI/CD debugging hell

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -80,10 +80,10 @@ jobs:
       - name: Upload natives
         uses: actions/upload-artifact@v4
         with:
-          name: linux-binary-${{ matrix.platform }}-${{ matrix.vulkan }}
-          path: src/main/resources/${{ matrix.arch }}/*
+          name: linux-natives-${{ matrix.platform }}-${{ matrix.vulkan }}
+          path: linux-build/*
 
-  build-windows-x64:
+  build-windows:
     needs: [download-models]
     runs-on: windows-latest
     strategy:
@@ -125,50 +125,54 @@ jobs:
       - name: Artifact windows x64
         uses: actions/upload-artifact@v4
         with:
-          name: windows-binary-x64
-          path: src/main/resources/windows-x64/*.dll
-  
-  build-windows-vulkan:
-    needs: [download-models]
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v4
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 22
-          distribution: 'temurin'
-      # Also install Vulkan 
-      - name: Install Vulkan SDK
-        uses: jakoch/install-vulkan-sdk-action@v1
-        with:
-          vulkan_version: 1.4.309.0
-          install_runtime: true
-          cache: true
-      - name: Setup project dir
-        run: |
-          git submodule update --init
-          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
-          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources
-      - name: Build
-        run: .\build_win_vulkan.ps1
-        shell: powershell
-      - name: Test
-        run: ./gradlew test
-      - name: Publish test report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure()
-        with:
-          report_paths: '**/build/test-results/test/test-*.xml'
-      - name: Upload Vulkan DLL artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: whisper-jni-vulkan
-          path: src/main/resources/windows-x64-vulkan/*.dll
+          name: windows-natives-${{ matrix.vulkan }}
+          path: windows-build/*.dll
+#
+#  build-windows-vulkan:
+#    needs: [download-models]
+#    runs-on: windows-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: actions/download-artifact@v4
+#      - uses: actions/setup-java@v4
+#        with:
+#          java-version: 22
+#          distribution: 'temurin'
+#      # Also install Vulkan
+#      - name: Install Vulkan SDK
+#        uses: jakoch/install-vulkan-sdk-action@v1
+#        with:
+#          vulkan_version: 1.4.309.0
+#          install_runtime: true
+#          cache: true
+#      - name: Setup project dir
+#        run: |
+#          git submodule update --init
+#          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
+#          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources
+#      - name: Build
+#        run: .\build_win_vulkan.ps1
+#        shell: powershell
+#      - name: Test
+#        run: ./gradlew test
+#      - name: Publish test report
+#        uses: mikepenz/action-junit-report@v5
+#        if: success() || failure()
+#        with:
+#          report_paths: '**/build/test-results/test/test-*.xml'
+#      - name: Upload Vulkan DLL artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: whisper-jni-vulkan
+#          path: src/main/resources/windows-x64-vulkan/*.dll
 
   build-mac-x64:
     needs: [download-models]
-    runs-on: macos-13
+    strategy:
+      matrix:
+        arch: [x86_64, aarch64]
+    # Can't we just build on macos-14 for both?? Need to test
+    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-13' || 'macos-14' }}
     steps:
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
@@ -184,7 +188,7 @@ jobs:
       - name: Build binary
         run: |
           export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
-          ./build_macos.sh x86_64
+          ./build_macos.sh ${{ matrix.arch }}
         # Apparently gradlew isn't executable by default
       - name: Test
         run: |
@@ -198,46 +202,12 @@ jobs:
       - name: Artifact macos x64
         uses: actions/upload-artifact@v4
         with:
-          name: mac-binary-x64
-          path: src/main/resources/mac-x64/*.dylib
-  
-  build-mac-aarch64:
-    needs: [download-models]
-    runs-on: macos-14
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v4
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 22
-          distribution: 'temurin'
-      - name: Setup project dir
-        run: |
-          git submodule update --init
-          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
-          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources
-      - name: Build binary
-        run: |
-          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
-          ./build_macos.sh aarch64
-      - name: Test
-        run: |
-          chmod +x ./gradlew
-          ./gradlew test
-      - name: Publish test report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure()
-        with:
-          report_paths: '**/build/test-results/**/*.xml'
-      - name: Artifact macos aarch64
-        uses: actions/upload-artifact@v4
-        with:
-          name: mac-binary-aarch64
-          path: src/main/resources/mac-aarch64/*.dylib
+          name: mac-natives-${{ matrix.arch }}
+          path: mac-build/*.dylib
 
   publish:
     runs-on: ubuntu-latest
-    needs: [download-models, build-linux, build-windows-x64, build-windows-vulkan, build-mac-x64, build-mac-aarch64]
+    needs: [download-models, build-linux, build-windows, build-mac]
     steps:
     - uses: actions/checkout@v4
     - uses: actions/download-artifact@v4
@@ -250,14 +220,14 @@ jobs:
     - name: Move natives
       run: |
         find ./src/main/resources -name ".gitkeep" -type f -delete
-        mv ./linux-binary-x64-ON/*.so ./src/main/resources/linux-x64-vulkan/
-        mv ./linux-binary-aarch64-ON/*.so ./src/main/resources/linux-aarch64-vulkan/
-        mv ./linux-binary-x64-OFF/*.so ./src/main/resources/linux-x64/
-        mv ./linux-binary-aarch64-OFF/*.so ./src/main/resources/linux-aarch64/
-        mv ./windows-binary-x64/*.dll ./src/main/resources/windows-x64/
-        mv ./whisper-jni-vulkan/*.dll ./src/main/resources/windows-x64-vulkan/
-        mv ./mac-binary-x64/*.dylib ./src/main/resources/mac-x64/
-        mv ./mac-binary-aarch64/*.dylib ./src/main/resources/mac-aarch64/
+#        mv ./linux-natives-x64-ON/*.so ./src/main/resources/linux-x64-vulkan/
+#        mv ./linux-natives-aarch64-ON/*.so ./src/main/resources/linux-aarch64-vulkan/
+        mv ./linux-natives-x64-OFF/*.so ./src/main/resources/linux-x64/
+        mv ./linux-natives-aarch64-OFF/*.so ./src/main/resources/linux-aarch64/
+        mv ./windows-natives/*.dll ./src/main/resources/windows-x64/
+#        mv ./whisper-jni-vulkan/*.dll ./src/main/resources/windows-x64-vulkan/
+        mv ./mac-natives-x64/*.dylib ./src/main/resources/mac-x64/
+        mv ./mac-natives-aarch64/*.dylib ./src/main/resources/mac-aarch64/
     - name: Setup project dir
       run: |
         git submodule update --init
